# Generated by Django 3.2.4 on 2021-06-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210610_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
